const index = {
  seriesList: [
    {
      tmdb: {
        id: "130270",
        type: "tv",
        season: 1,
        vote_average: 7.5,
        vote_count: 27,
      },
      imdb: { id: "tt27460313", vote_average: 8, vote_count: 5404 },
      created: { time: "2025-08-13T01:54:57.000Z" },
      modified: { time: "2025-08-13T01:54:57.000Z" },
      _id: "dd1dd4134f0a5d5dfd78523a1291be3b",
      name: "Ngọc Cốt Dao",
      slug: "ngoc-cot-dao",
      origin_name: "The Longest Promise",
      alternative_names: [
        "玉骨谣",
        "The Longest Promisse",
        "옥골요",
        "ลำนำกระดูกหยก",
        "โชคชะตาฟ้าลิขิต ความคะนึงหากลายเป็นชะตากรรม",
        "Jade Bone Ballad",
        "玉骨遥",
      ],
      content:
        "<p>Thời Ảnh - thế tử Không Tang cao ngạo lạnh lùng và Chu Nhan - quận chúa Xích tộc nhiệt tình trượng nghĩa nên duyên định mệnh nhờ ơn một đóa hoa, rồi lại tình cờ trở thành thầy trò bầu bạn ba năm. Tà ác trỗi dậy, Không Tang đứng trước nguy cơ diệt vong. Thời Ảnh lầm tưởng Chỉ Uyên – giao nhân cùng lớn lên với Chu Nhan là Hải hoàng, do đó đã tự tay phong ấn Chỉ Uyên. Cuối cùng, Chu Nhan rút Ngọc Cốt đâm về phía Thời Ảnh, lời sấm thành sự thật. Thế nhưng số phận đã sớm thay đổi kể từ ngày trái tim ai đó trao đi...</p>",
      type: "series",
      status: "completed",
      thumb_url:
        "https://phimimg.com/upload/vod/20250813-1/f21b147903b4e86271440e76d3ee0d2c.jpg",
      poster_url:
        "https://phimimg.com/upload/vod/20250813-1/e6bf01c709c2c30559f71e499106eebd.jpg",
      is_copyright: false,
      sub_docquyen: false,
      chieurap: false,
      is_published: true,
      trailer_url: "https://www.youtube.com/watch?v=_r96odMS9NM",
      time: "45 phút/tập",
      episode_current: "Hoàn Tất (40/40)",
      episode_total: 40,
      quality: "FHD",
      lang: "Vietsub + Thuyết Minh",
      lang_key: ["vs", "tm"],
      notify: "",
      showtimes: "",
      year: 2023,
      view: 7,
      actor: [
        "Tiêu Chiến",
        "Nhậm Mẫn",
        "Vương Sở Nhiên",
        "Phương Dật Luân",
        "Hàn Đống",
      ],
      director: ["Giang Gia Quân"],
      category: [
        {
          name: "Chính Kịch",
          slug: "chinh-kich",
          id: "37a7b38b6184a5ebd3c43015aa20709d",
        },
        {
          name: "Cổ Trang",
          slug: "co-trang",
          id: "3a17c7283b71fa84e5a8d76fb790ed3e",
        },
        {
          name: "Tình Cảm",
          slug: "tinh-cam",
          id: "bb2b4b030608ca5984c8dd0770f5b40b",
        },
        {
          name: "Tâm Lý",
          slug: "tam-ly",
          id: "a7b065b92ad356387ef2e075dee66529",
        },
      ],
      country: [
        {
          name: "Trung Quốc",
          slug: "trung-quoc",
          id: "3e075636c731fe0f889c69e0bf82c083",
        },
      ],
    },
    {
      tmdb: {
        id: "135354",
        type: "tv",
        season: 1,
        vote_average: 6.7,
        vote_count: 3,
      },
      imdb: { id: "tt15655354", vote_average: 0, vote_count: 0 },
      created: { time: "2024-10-15T13:49:46.000Z" },
      modified: { time: "2024-10-16T18:25:26.000Z" },
      _id: "93af461084793fe02a394f7efb844716",
      name: "Xin Chào, Tạm Biệt Mẹ",
      slug: "xin-chao-tam-biet-me",
      origin_name: "The Last Goodbye to Mama",
      alternative_names: [
        "99 Things With My Mom , Zai Jian La Mu Qin Da Ren , 再见啦！母亲大人 , 与母亲的99件小事",
        "再见啦！母亲大人",
        "再见啦母亲大人",
        "The Last Goodbye To Mama",
        "니호!모친대인 : 안녕! 엄마",
        "您好！母亲大人",
      ],
      content:
        "<p>Xin Chào, Tạm Biệt Mẹ - The Last Goodbye To Mama là câu chuyện cảm động xoay quanh cuộc sống của hai mẹ con đến từ một thị trấn nhỏ ở Tô Bắc. Thanh niên 18 tuổi Ding Xiao Jun được nhận vào một trường đại học ở Bắc Kinh và bắt đầu cuộc sống nổi loạn, ngỗ nghịch. Xiao Jun đã không thể tốt nghiệp đại học nếu như mẹ anh không đến xin nhà trường. Sau khi tốt nghiệp, Ding Xiao Jun bị lừa hết số tiền kiếm được và trở thành một kẻ ăn bám trong nhiều tháng. Bắt đầu hiểu được tất cả những khó khăn mà mẹ đã phải trải qua, Xiao Jun đã cố gắng để được quay về với mẹ. Trong đêm giao thừa, Ding Xiao Jun nhận được tin trúng tuyển vào 1 công ty ở Bắc Kinh, cũng là lúc anh nhận tin mẹ bị chẩn đoán mắc bệnh nan y. Ding Xiao Jun phải đối mặt với hai lựa chọn: tiếp tục xây dựng sự nghiệp ở Bắc Kinh hay về nhà với mẹ trong những ngày cuối đời của bà.</p>",
      type: "series",
      status: "completed",
      thumb_url:
        "https://phimimg.com/upload/vod/20241015-1/d64ce4b699d29a199fda1a0d202a3bfe.jpg",
      poster_url:
        "https://phimimg.com/upload/vod/20241015-1/e13f5192b36c8fa3d6d83296dd5edb2b.jpg",
      is_copyright: false,
      sub_docquyen: false,
      chieurap: false,
      is_published: true,
      trailer_url: "",
      time: "45 phút/tập",
      episode_current: "Hoàn Tất (30/30)",
      episode_total: 30,
      quality: "FHD",
      lang: "Vietsub",
      lang_key: ["vs"],
      notify: "",
      showtimes: "",
      year: 2021,
      view: 8,
      actor: [
        "董潔",
        "Yin Fang",
        "Lu Fangsheng",
        "王楚然",
        "Zhao Wei",
        "Lu Cai",
        "Chen Jiawen",
        "Jiang Xueming",
        "Zhang Yao",
        "Ran Xu",
        "Qu Shanshan",
        "Zeng Qi",
        "Gong Lei",
        "He Xuanlin",
        "Du Shuangyu",
        "Gong Zhengye",
        "Liang Yue Jun",
        "Zhou Dehua",
        "Cao Yanyan",
        "Han Xiuyi",
        "方悅喬",
        "Yin Yuhang",
        "Zhou Lula",
        "Zhang Le",
      ],
      director: ["Cao Dun", "Jing Chong"],
      category: [
        {
          name: "Gia Đình",
          slug: "gia-dinh",
          id: "a2492d6cbc4d58f115406ca14e5ec7b6",
        },
        {
          name: "Tình Cảm",
          slug: "tinh-cam",
          id: "bb2b4b030608ca5984c8dd0770f5b40b",
        },
      ],
      country: [
        {
          name: "Trung Quốc",
          slug: "trung-quoc",
          id: "3e075636c731fe0f889c69e0bf82c083",
        },
      ],
    },
    {
      tmdb: {
        id: "112966",
        type: "tv",
        season: 1,
        vote_average: 4.8,
        vote_count: 5,
      },
      imdb: { id: "tt13550418", vote_average: 8.3, vote_count: 74 },
      created: { time: "2025-12-03T12:13:28.000Z" },
      modified: { time: "2026-06-15T00:40:53.000Z" },
      _id: "ecbc7b96b9ec7951187d0da02230773d",
      name: "Cuộc Phiêu Lưu Của Chiếc Nhẫn",
      slug: "cuoc-phieu-luu-cua-chiec-nhan",
      origin_name: "Adventure Of The Ring",
      alternative_names: [
        "戒指流浪記",
        "La aventura del anillo",
        "Adventure of the Ring",
      ],
      content:
        "<p>Hoàng Dịch Chi đánh mất chiếc nhẫn trên tàu điện ngầm vào đúng ngày anh định cầu hôn. Chiếc nhẫn qua tay 7 người và tạo nên 7 câu chuyện lãng mạn.</p>",
      type: "series",
      status: "completed",
      thumb_url:
        "https://phimimg.com/upload/vod/20251203-1/1a8c61ec02b321a57f890099730fe34f.jpg",
      poster_url:
        "https://phimimg.com/upload/vod/20251203-1/17fffa03a28602498d22471f36bb33c2.jpg",
      is_copyright: false,
      sub_docquyen: false,
      chieurap: false,
      is_published: true,
      trailer_url: "https://www.youtube.com/watch?v=qIXmhMlw9wg",
      time: "45 phút/tập",
      episode_current: "Hoàn Tất (8/8)",
      episode_total: 8,
      quality: "FHD",
      lang: "Vietsub",
      lang_key: ["vs"],
      notify: "",
      showtimes: "",
      year: 2020,
      view: 31,
      actor: ["Chris Wang", "Allison Lin"],
      director: ["Toyoharu Kitamura"],
      category: [
        {
          name: "Chính Kịch",
          slug: "chinh-kich",
          id: "37a7b38b6184a5ebd3c43015aa20709d",
        },
        {
          name: "Hài Hước",
          slug: "hai-huoc",
          id: "ba6fd52e5a3aca80eaaf1a3b50a182db",
        },
        {
          name: "Tâm Lý",
          slug: "tam-ly",
          id: "a7b065b92ad356387ef2e075dee66529",
        },
      ],
      country: [
        {
          name: "Đài Loan",
          slug: "dai-loan",
          id: "559fea9881e3a6a3e374b860fa8fb782",
        },
      ],
    },
    {
      tmdb: {
        id: "230311",
        type: "tv",
        season: 1,
        vote_average: 7.5,
        vote_count: 4,
      },
      imdb: { id: "tt28131816", vote_average: 7.4, vote_count: 39 },
      created: { time: "2026-06-15T15:06:13.000Z" },
      modified: { time: "2026-07-04T06:08:03.000Z" },
      _id: "e7004e2ce735b7e8af316bdc0cb84fad",
      name: "Tình Yêu Có Pháo Hoa",
      slug: "tinh-yeu-co-phao-hoa",
      origin_name: "Love Has Fireworks",
      alternative_names: [
        "爱情有烟火",
        "我们住在一起",
        "愛情有煙火",
        "Ai Qing You Yan Huo",
        "We live together",
        "Shining Character",
      ],
      content:
        "<p>Tình Yêu Có Pháo Hoa là bộ phim tình cảm đô thị xoay quanh Lý Diệc Phi, một chuyên gia ngân hàng đầu tư sa cơ sau thất bại trong công việc, và Tiền Phi, cô gái đang chật vật đối mặt với cú sốc thất tình lẫn thất nghiệp. Tình cờ trở thành bạn cùng nhà để giảm bớt gánh nặng tài chính, cả hai liên tục va chạm vì khác biệt về tính cách, hoàn cảnh và quan điểm sống. Thế nhưng qua những ngày chung sống đầy dở khóc dở cười, họ dần thấu hiểu, động viên và giúp nhau trưởng thành, từ đó viết nên một câu chuyện tình yêu ngọt ngào giữa lòng thành phố hiện đại.</p>",
      type: "series",
      status: "completed",
      thumb_url:
        "https://phimimg.com/upload/vod/20260615-1/c2def538c0d18eeace93e7a6c358679f.jpg",
      poster_url:
        "https://phimimg.com/upload/vod/20260615-1/db63587e4b529e6604d423307c8d0258.jpg",
      is_copyright: false,
      sub_docquyen: false,
      chieurap: false,
      is_published: true,
      trailer_url: "https://www.youtube.com/watch?v=AYygGWCkbsQ",
      time: "45 phút/tập",
      episode_current: "Hoàn Tất (36/36)",
      episode_total: 36,
      quality: "FHD",
      lang: "Vietsub + Thuyết Minh",
      lang_key: ["vs", "tm"],
      notify: "",
      showtimes: "",
      year: 2026,
      view: 81,
      actor: [
        "Đàn Kiện Thứ",
        "Vương Sở Nhiên",
        "Lý Nãi Văn",
        "Lý Hân Trạch",
        "Khương Bội Dao",
        "Trịnh Thủy Tinh",
        "Lưu Nhuế Lân",
      ],
      director: ["Sử Thành Nghiệp"],
      category: [
        {
          name: "Chính Kịch",
          slug: "chinh-kich",
          id: "37a7b38b6184a5ebd3c43015aa20709d",
        },
        {
          name: "Tình Cảm",
          slug: "tinh-cam",
          id: "bb2b4b030608ca5984c8dd0770f5b40b",
        },
        {
          name: "Tâm Lý",
          slug: "tam-ly",
          id: "a7b065b92ad356387ef2e075dee66529",
        },
      ],
      country: [
        {
          name: "Trung Quốc",
          slug: "trung-quoc",
          id: "3e075636c731fe0f889c69e0bf82c083",
        },
      ],
    },
    {
      tmdb: {
        id: "110834",
        type: "tv",
        season: 1,
        vote_average: 8,
        vote_count: 3,
      },
      imdb: { id: "tt12363180", vote_average: 0, vote_count: 0 },
      created: { time: "2024-11-24T16:59:32.000Z" },
      modified: { time: "2024-11-25T01:41:58.000Z" },
      _id: "74633dc3ab2e714eeba0bd6624b0799d",
      name: "Cùng Nhau",
      slug: "cung-nhau",
      origin_name: "With You",
      alternative_names: [
        "Zai Yi Qi",
        "Zai Yi Qi Tong Xing",
        "เพราะเรามีกัน",
        "Walk Together",
        "Together",
        "在一起",
      ],
      content:
        "<p>Dựa trên những câu chuyện có thật ở mọi ngành nghề trong thời gian chống dịch, thêm vào yếu tố nghệ thuật, để tạo nên hình ảnh quần chúng anh hùng có khóc có cười trên mặt trận tuyến đầu chống dịch. Bóc tách từng biểu hiện, thái độ chống dịch của mỗi người dân trong bức tranh toàn cảnh của cuộc chiến cam go, thể hiện tinh thần đoàn kết một lòng, cùng chung hoạn nạn của nhân dân Trung Quốc.</p>",
      type: "series",
      status: "completed",
      thumb_url:
        "https://phimimg.com/upload/vod/20241125-1/ed5e1e65ecda72474a0bd7a2569c8401.jpg",
      poster_url:
        "https://phimimg.com/upload/vod/20241125-1/07dc25fe3708e91547a0f22bdceac855.jpg",
      is_copyright: false,
      sub_docquyen: false,
      chieurap: false,
      is_published: true,
      trailer_url: "https://www.youtube.com/watch?v=unGdRz3H8HY",
      time: "44 phút/tập",
      episode_current: "Hoàn Tất (20/20)",
      episode_total: 20,
      quality: "FHD",
      lang: "Vietsub",
      lang_key: ["vs"],
      notify: "",
      showtimes: "",
      year: 2020,
      view: 6,
      actor: [],
      director: ["Zhang Li", "Shen Yan"],
      category: [
        {
          name: "Chính Kịch",
          slug: "chinh-kich",
          id: "37a7b38b6184a5ebd3c43015aa20709d",
        },
      ],
      country: [
        {
          name: "Trung Quốc",
          slug: "trung-quoc",
          id: "3e075636c731fe0f889c69e0bf82c083",
        },
      ],
    },
    {
      tmdb: {
        id: null,
        type: null,
        season: null,
        vote_average: 0,
        vote_count: 0,
      },
      imdb: { id: null, vote_average: 0, vote_count: 0 },
      modified: { time: "2024-09-29T13:22:35.000Z" },
      _id: "bd2ef2fc182ccd107c829cfa92fba995",
      name: "Thượng Thực",
      slug: "thuong-thuc",
      origin_name: "Royal Feast",
      alternative_names: [],
      type: "series",
      thumb_url:
        "https://phimimg.com/upload/vod/20240825-1/f981a0a94ba5cf9a01007efc2a1d9e82.jpg",
      poster_url:
        "https://phimimg.com/upload/vod/20240825-1/0e35912df42ad66a567c5cec21455fba.jpg",
      sub_docquyen: false,
      chieurap: false,
      time: "45 phút/tập",
      episode_current: "Hoàn Tất (40/40)",
      quality: "FHD",
      lang: "Vietsub + Thuyết Minh + Lồng Tiếng",
      lang_key: ["vs", "tm", "lt"],
      year: 2022,
      category: [
        {
          name: "Chính Kịch",
          slug: "chinh-kich",
          id: "37a7b38b6184a5ebd3c43015aa20709d",
        },
        {
          name: "Cổ Trang",
          slug: "co-trang",
          id: "3a17c7283b71fa84e5a8d76fb790ed3e",
        },
      ],
      country: [
        {
          name: "Trung Quốc",
          slug: "trung-quoc",
          id: "3e075636c731fe0f889c69e0bf82c083",
        },
      ],
      last_episodes: [
        { server_name: "Vietsub", is_ai: false, name: "Tập 40" },
        { server_name: "Lồng Tiếng", is_ai: false, name: "Tập 40" },
        { server_name: "Thuyết Minh", is_ai: false, name: "Tập 40" },
      ],
    },
    {
      tmdb: {
        id: "154770",
        type: "tv",
        season: 4,
        vote_average: 6.4,
        vote_count: 10,
      },
      imdb: { id: "tt30985733", vote_average: 0, vote_count: 23 },
      created: { time: "2025-09-05T17:50:20.000Z" },
      modified: { time: "2025-09-06T13:21:21.000Z" },
      _id: "b191b91cbd52c3fcff21b16d6aafa259",
      name: "Xin Chào, Thứ Bảy (Mùa 4)",
      slug: "xin-chao-thu-bay-mua-4",
      origin_name: "Hello, Saturday (Season 4)",
      alternative_names: ["H!6", "Hi6", "你好，星期六"],
      content:
        "<p>Xin Chào Thứ 7&quot;được sản xuất bởi đài truyền hình Hồ Nam, với sự dẫn dắt của các MC He Jiong, Ngô Tắc Lâm và Tiểu Dương (MC ảo thực tập).Đinh Thành Tân, Đan Kiện Tư, Tần Tiêu Hiền, Thái Văn Tĩnh, Lý Tuyết Khâm, VươngHạcĐệ, Dương Địch đảm nhận chương trình tạp kỹ nghệ thuật thú vị của nhóm Sáu Tốt. Chương trình mỗi kỳ sẽ mời một vài khách mời tham gia ghi hình, với bối cảnh là khu phố mới được xây dựng Haoliu, mang không khí đời sống bình dị vào trường quay, thể hiện đủ mọi sắc thái của cuộc sống phố phường.</p>",
      type: "tvshows",
      status: "ongoing",
      thumb_url:
        "https://phimimg.com/upload/vod/20250906-1/07c73000d63bf4268271972df817f2d4.jpg",
      poster_url:
        "https://phimimg.com/upload/vod/20250906-1/dae367944bdfa44a99b26ecae7568481.jpg",
      is_copyright: false,
      sub_docquyen: false,
      chieurap: false,
      is_published: true,
      trailer_url: "",
      time: "90 phút/tập",
      episode_current: "Tập 35",
      episode_total: 44,
      quality: "FHD",
      lang: "Vietsub",
      lang_key: ["vs"],
      notify: "",
      showtimes: "",
      year: 2025,
      view: 9,
      actor: ["He Jiong", "Li Xueqin", "Yang Di", "Ding Chengxin", "Wu Ze Lin"],
      director: [],
      category: [
        {
          name: "Chính Kịch",
          slug: "chinh-kich",
          id: "37a7b38b6184a5ebd3c43015aa20709d",
        },
        {
          name: "Hài Hước",
          slug: "hai-huoc",
          id: "ba6fd52e5a3aca80eaaf1a3b50a182db",
        },
      ],
      country: [
        {
          name: "Trung Quốc",
          slug: "trung-quoc",
          id: "3e075636c731fe0f889c69e0bf82c083",
        },
      ],
    },
    {
      tmdb: {
        id: "237882",
        type: "tv",
        season: 1,
        vote_average: 7.7,
        vote_count: 10,
      },
      imdb: { id: "tt29363632", vote_average: 7.7, vote_count: 385 },
      created: { time: "2024-08-14T02:33:22.000Z" },
      modified: { time: "2026-01-27T02:30:00.000Z" },
      _id: "fee119ef73799cd0aa1f036cfa268930",
      name: "Liễu Chu Ký",
      slug: "lieu-chu-ky",
      origin_name: "Are You The One",
      alternative_names: [
        "Você é o Único",
        "A Pessoa Prometida",
        "Liu Zhou Ji",
        "Jiao Cang",
        "娇藏",
        "ซ่อนรักชายาลับ",
        "Liu Zhou Story",
        "Hidden Charm",
        "Are You the One",
        "柳舟记",
      ],
      content:
        "<p>Bộ phim kể về câu chuyện tình yêu &quot;mèo vờn chuột&quot; giữa vị vương gia xảo quyệt, bụng dạ khó lường Thôi Hành Chu và nữ trại chủ thông minh, tinh quái Liễu Miên Đường. Thôi Hành Chu được giao nhiệm vụ tiêu diệt đám cướp ở Ngưỡng Sơn, trong một lần tình cờ đã cứu mạng Liễu Miên Đường - người chưa từng gặp nhưng lại chính là kẻ thù đáng gờm của mình và lại tưởng nhầm rằng cô là thiếp được yêu chiều của thủ lĩnh Ngưỡng Sơn. Sau khi trọng thương và tỉnh dậy, Liễu Miên Đường mất đi một phần ký ức và nhận nhầm Thôi Hành Chu là &quot;phu quân&quot; của mình, Thôi Cửu. Thôi Hành Chu tương kế tựu kế, giả làm Thôi Cửu - một thương nhân thất bại, chán nản và đóng giả thành phu thê với cô. Không ngờ dù mất trí nhớ và phải trở thành một nữ nhân lo liệu chuyện gia đình, Liễu Miên Đường vẫn thể hiện sự can đảm và tài trí phi thường của mình khi mở một cửa tiệm đồ sứ và kinh doanh rất phát đạt.</p>",
      type: "series",
      status: "completed",
      thumb_url:
        "https://phimimg.com/upload/vod/20260126-1/77f7083cb564a4c050b9de49d060e21b.jpg",
      poster_url:
        "https://phimimg.com/upload/vod/20260126-1/d76dce390859b6e1e3b503a8ada22096.jpg",
      is_copyright: false,
      sub_docquyen: false,
      chieurap: false,
      is_published: true,
      trailer_url: "https://www.youtube.com/watch?v=j6jUsB_0ZD4",
      time: "46 phút/tập",
      episode_current: "Hoàn Tất (40/40)",
      episode_total: 40,
      quality: "FHD",
      lang: "Vietsub + Thuyết Minh + Lồng Tiếng",
      lang_key: ["vs", "tm", "lt"],
      notify: "",
      showtimes: "",
      year: 2024,
      view: 26,
      actor: [
        "Trương Vãn Ý",
        "Vương Sở Nhiên",
        "Lưu Lệnh Tư",
        "Thường Hoa Sâm",
        "Trương Thỉ",
        "Viên Vũ Huyên",
        "Lại Nghệ",
      ],
      director: ["Lưu Quốc Nam"],
      category: [
        {
          name: "Hành Động",
          slug: "hanh-dong",
          id: "9822be111d2ccc29c7172c78b8af8ff5",
        },
        {
          name: "Phiêu Lưu",
          slug: "phieu-luu",
          id: "66c78b23908113d478d8d85390a244b4",
        },
        {
          name: "Chính Kịch",
          slug: "chinh-kich",
          id: "37a7b38b6184a5ebd3c43015aa20709d",
        },
        {
          name: "Tình Cảm",
          slug: "tinh-cam",
          id: "bb2b4b030608ca5984c8dd0770f5b40b",
        },
        {
          name: "Tâm Lý",
          slug: "tam-ly",
          id: "a7b065b92ad356387ef2e075dee66529",
        },
        {
          name: "Cổ Trang",
          slug: "co-trang",
          id: "3a17c7283b71fa84e5a8d76fb790ed3e",
        },
      ],
      country: [
        {
          name: "Trung Quốc",
          slug: "trung-quoc",
          id: "3e075636c731fe0f889c69e0bf82c083",
        },
      ],
    },
    {
      tmdb: {
        id: null,
        type: null,
        season: null,
        vote_average: 0,
        vote_count: 0,
      },
      imdb: { id: null, vote_average: 0, vote_count: 0 },
      modified: { time: "2025-03-26T07:12:51.000Z" },
      _id: "dfc0ddf31f87eeef737ffb16705467b5",
      name: "Khói Lửa Nhân Gian Của Tôi",
      slug: "khoi-lua-nhan-gian-cua-toi",
      origin_name: "Fireworks Of My Heart",
      alternative_names: [],
      type: "series",
      thumb_url:
        "https://phimimg.com/upload/vod/20240815-1/5575adcae0a157a0c1ea8b9b08daa589.jpg",
      poster_url:
        "https://phimimg.com/upload/vod/20240815-1/008e6a063b10e760b0fcd86a72f85708.jpg",
      sub_docquyen: false,
      chieurap: false,
      time: "45 phút/tập",
      episode_current: "Hoàn Tất (40/40)",
      quality: "FHD",
      lang: "Vietsub + Thuyết Minh",
      lang_key: ["vs", "tm"],
      year: 2023,
      category: [
        {
          name: "Hành Động",
          slug: "hanh-dong",
          id: "9822be111d2ccc29c7172c78b8af8ff5",
        },
        {
          name: "Phiêu Lưu",
          slug: "phieu-luu",
          id: "66c78b23908113d478d8d85390a244b4",
        },
        {
          name: "Chính Kịch",
          slug: "chinh-kich",
          id: "37a7b38b6184a5ebd3c43015aa20709d",
        },
        {
          name: "Tình Cảm",
          slug: "tinh-cam",
          id: "bb2b4b030608ca5984c8dd0770f5b40b",
        },
        {
          name: "Tâm Lý",
          slug: "tam-ly",
          id: "a7b065b92ad356387ef2e075dee66529",
        },
      ],
      country: [
        {
          name: "Trung Quốc",
          slug: "trung-quoc",
          id: "3e075636c731fe0f889c69e0bf82c083",
        },
      ],
      last_episodes: [
        { server_name: "Vietsub", is_ai: false, name: "Tập 40" },
        { server_name: "Thuyết Minh", is_ai: false, name: "Tập 40" },
      ],
    },
    {
      tmdb: {
        id: null,
        type: null,
        season: null,
        vote_average: 0,
        vote_count: 0,
      },
      imdb: { id: null, vote_average: 0, vote_count: 0 },
      modified: { time: "2024-01-08T07:35:49.000Z" },
      _id: "20337d9ceb6b6438f1195b399ed0a0e2",
      name: "Nghe Nói Em Thích Tôi",
      slug: "nghe-noi-em-thich-toi",
      origin_name: "Have A Crush On You",
      alternative_names: [],
      type: "series",
      thumb_url:
        "https://phimimg.com/upload/vod/20231219-1/578ce080d5603b33181a5de59859c5d9.jpg",
      poster_url:
        "https://phimimg.com/upload/vod/20231219-1/8013c4f6c28d2b180d00a4bccf535cb6.jpg",
      sub_docquyen: false,
      chieurap: false,
      time: "45 phút/tập",
      episode_current: "Hoàn Tất (36/36)",
      quality: "FHD",
      lang: "Thuyết Minh",
      lang_key: ["tm"],
      year: 2023,
      category: [
        {
          name: "Tình Cảm",
          slug: "tinh-cam",
          id: "bb2b4b030608ca5984c8dd0770f5b40b",
        },
        {
          name: "Chính Kịch",
          slug: "chinh-kich",
          id: "37a7b38b6184a5ebd3c43015aa20709d",
        },
        {
          name: "Bí Ẩn",
          slug: "bi-an",
          id: "2fb53017b3be83cd754a08adab3e916c",
        },
      ],
      country: [
        {
          name: "Trung Quốc",
          slug: "trung-quoc",
          id: "3e075636c731fe0f889c69e0bf82c083",
        },
      ],
      last_episodes: [
        { server_name: "Thuyết Minh", is_ai: false, name: "Tập 36" },
      ],
    },
    {
      tmdb: {
        id: "280632",
        type: "tv",
        season: 1,
        vote_average: 8.3,
        vote_count: 21,
      },
      imdb: { id: "tt35231547", vote_average: 8.3, vote_count: 90 },
      created: { time: "2026-02-06T04:06:21.000Z" },
      modified: { time: "2026-03-09T00:47:05.000Z" },
      _id: "6c9084f3201fb66874073cffff5618d0",
      name: "Còn Ra Thể Thống Gì Nữa?",
      slug: "con-ra-the-thong-gi-nua",
      origin_name: "How Dare You!?",
      alternative_names: [
        "Cheng He Ti Tong",
        "成何体统剧版",
        "成何体统(真人版)",
        "成何體統",
        "How are you?",
        "How Dare You!？",
        "成何体统",
      ],
      content:
        "<p>Vương Thúy Hoa xuyên không vào thế giới tiểu thuyết và hợp tác với Trương Tam để chống lại thiên tai, ổn định biên cương và đánh bại kẻ thù. Khi số phận trêu ngươi buộc họ phải đối mặt với sinh tử, cô chọn cứu anh bằng cách biến chất độc thành thuốc, và cuối cùng cả hai sống sót, chứng kiến thành quả mà họ cùng tạo dựng.</p>",
      type: "series",
      status: "completed",
      thumb_url:
        "https://phimimg.com/upload/vod/20260206-1/65bde3b8112ed04109a3d1f15db3d759.jpg",
      poster_url:
        "https://phimimg.com/upload/vod/20260206-1/e69a8f905dd7f143d7e2f25025a2f433.jpg",
      is_copyright: false,
      sub_docquyen: false,
      chieurap: false,
      is_published: true,
      trailer_url: "https://www.youtube.com/watch?v=dpt09n7MUAw",
      time: "45 phút/tập",
      episode_current: "Hoàn Tất (32/32)",
      episode_total: 32,
      quality: "FHD",
      lang: "Vietsub + Thuyết Minh",
      lang_key: ["vs", "tm"],
      notify: "",
      showtimes: "",
      year: 2026,
      view: 25,
      actor: ["Vương Sở Nhiên", "Thừa Lỗi", "Đường Tiểu Thiên", "Hồ Dị Uyển"],
      director: ["Lưu Hải Ba", "Vương Lệ"],
      category: [
        {
          name: "Chính Kịch",
          slug: "chinh-kich",
          id: "37a7b38b6184a5ebd3c43015aa20709d",
        },
        {
          name: "Bí Ẩn",
          slug: "bi-an",
          id: "2fb53017b3be83cd754a08adab3e916c",
        },
        {
          name: "Tình Cảm",
          slug: "tinh-cam",
          id: "bb2b4b030608ca5984c8dd0770f5b40b",
        },
        {
          name: "Tâm Lý",
          slug: "tam-ly",
          id: "a7b065b92ad356387ef2e075dee66529",
        },
        {
          name: "Cổ Trang",
          slug: "co-trang",
          id: "3a17c7283b71fa84e5a8d76fb790ed3e",
        },
        {
          name: "Viễn Tưởng",
          slug: "vien-tuong",
          id: "68564911f00849030f9c9c144ea1b931",
        },
      ],
      country: [
        {
          name: "Trung Quốc",
          slug: "trung-quoc",
          id: "3e075636c731fe0f889c69e0bf82c083",
        },
      ],
    },
  ],
  singleList: [],
  profile: {
    adult: false,
    also_known_as: [
      "Wang Churan",
      "Wang Chu Ran",
      "Vương Sở Nhiên",
      "Churan Wang ",
    ],
    biography: "",
    birthday: "1999-01-21",
    deathday: null,
    gender: 1,
    homepage: "https://m.weibo.cn/u/3828809034",
    id: 2271369,
    imdb_id: "nm10716401",
    known_for_department: "Acting",
    name: "Vương Sở Nhiên",
    place_of_birth: "Shanghai, China",
    popularity: 3.5162,
    profile_path: "/jHSQ3ZOfFhszPuz1kG0zkpHwe8N.jpg",
  },
};
